CREATE TABLE IF NOT EXISTS "Message" (
  id UUID PRIMARY KEY NOT NULL,
  "telegramId" VARCHAR(255) NOT NULL,
  "userMessage" TEXT NOT NULL,
  "aiResponse" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
